In [1]:
import pandas as pd
import numpy as np
import pint
import pint_pandas

from ensembler.util.units import unit_registry
from ensembler.potentials import OneD
from ensembler.system.basic_system import system

In [2]:
h = OneD.harmonicOscillatorPotential(unitless=False)

In [14]:
h.V_functional

Voffset + 0.5*k*(r - r_0)**2

In [3]:
print(str(h))

harmonicOscillatorPotential
	States: 1
	Dimensions: 1

	Functional:
 		V:	Voffset + 0.5*k*(r - r_0)**2
		dVdpos:	0.5*k*(2*r - 2*r_0)

	Simplified Function
		V:	0.5*r**2
		dVdpos:	1.0*r

	Constants: 
		k: 			1.0 kJ / nm ** 2
		r_0: 			0.0 nm
		Voffset: 			0.0 kJ
		nDimensions: 			1
		nStates: 			1




In [4]:
rs = np.arange(10)*unit_registry.nm
rs


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) <Unit('nanometer')>

In [5]:
h.ene(rs)

array([ 0. ,  0.5,  2. ,  4.5,  8. , 12.5, 18. , 24.5, 32. , 40.5]) <Unit('kilojoule')>

In [6]:
h.force(rs)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]) <Unit('kilojoule / nanometer')>

In [7]:
h.argsV

(1 <Unit('kilojoule / nanometer ** 2')>,
 1 <Unit('nanometer')>,
 1 <Unit('kilojoule')>,
 1,
 1,
 1 <Unit('nanometer')>)

In [8]:
h._solve_units(h.dVdpos,
               unit_registry.nm*1)

<Unit('nanometer')>

In [9]:
x = h.ff(*h.argsV)

In [10]:
import pint
pint.Quantity(x)

1.0 <Unit('nanometer')>

In [11]:
h.ff

<function _lambdifygenerated(k, r_0, Voffset, nDimensions, nStates, r)>

In [12]:
h.dVdpos_functional

0.5*k*(2*r - 2*r_0)

In [13]:
h.dVdpos_functional.free_symbols

{k, r, r_0}